/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package slutprojekt;

import oru.inf.InfDB;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfException;
/**
 *
 * @author krist
 */
public class soka_agent extends javax.swing.JFrame {
    private InfDB idb;
    private static String email;
    private HashMap<String, String> info = new HashMap<>();
    DefaultTableModel model;
    private String val;
    private String sok;
    private String datum;
    /**
     * Creates new form soka_agent
     */
    public soka_agent(InfDB idb, String email, String namn) {
        initComponents();
        this.idb = idb;
        email_L.setText(email);
        agent_L.setText(namn);
        model = (DefaultTableModel) agent_tb.getModel();
        val="";
    }
//Metod för att hämta om agenten är områdeschef eller kontorschef.
    private String getBefattning (String agentID){

        String befattning = "Fältagent";

        try {


            if (idb.fetchColumn("SELECT Agent_ID FROM omradeschef").contains(agentID)) {

                befattning = "Områdeschef";

            } else if (idb.fetchColumn("SELECT Agent_ID FROM kontorschef").contains(agentID)) {

                befattning = "Kontorschef";

            }

        } catch (InfException ex) {
            Logger.getLogger(soka_agent.class.getName()).log(Level.SEVERE, null, ex);
        }
        return befattning;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        val_cb = new javax.swing.JComboBox<>();
        sok_agent_tf = new javax.swing.JTextField();
        sok_agent_btn = new javax.swing.JButton();
        datum_tf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        agent_tb = new javax.swing.JTable();
        avsluta_btn = new javax.swing.JButton();
        tillbaka_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        email_L = new javax.swing.JLabel();
        agent_L = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sök Agent");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sök ");

        val_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj", "Namn", "Anställningsdatum", "ID", "Område", "Kategori (Områdeschef)", "Kategori (Fältagent)", "Kategori (Kontorschef)", "Telefonnummer", "Epost", " " }));
        val_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_cbActionPerformed(evt);
            }
        });

        sok_agent_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sok_agent_tfActionPerformed(evt);
            }
        });

        sok_agent_btn.setText("Sök Agent");
        sok_agent_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sok_agent_btnActionPerformed(evt);
            }
        });

        agent_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Agent_ID", "Anställningsdatum", "Epost", "Losenord", "Namn", "Telefon", "Område", "Administratör", "Kategori"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(agent_tb);

        avsluta_btn.setText("Avsluta");
        avsluta_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avsluta_btnActionPerformed(evt);
            }
        });

        tillbaka_btn.setText("Tillbaka");
        tillbaka_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tillbaka_btnActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Inloggad som ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Epost");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agent_L, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(email_L, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agent_L, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(98, 98, 98))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 636, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tillbaka_btn)
                    .addComponent(avsluta_btn))
                .addGap(16, 16, 16))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(121, 121, 121)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(datum_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(val_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(sok_agent_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(24, 24, 24)
                                    .addComponent(sok_agent_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(avsluta_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tillbaka_btn)))
                .addContainerGap(525, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(42, 42, 42)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sok_agent_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(val_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sok_agent_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(datum_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void val_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_cbActionPerformed
//Metod för att få ett förutbestämt sökord i sökfältet beroende på val i combobox.
        sok = sok_agent_tf.getText(); // uppdaterar
        sok_agent_tf.setEnabled(true);

        val_cb.addActionListener(sok_agent_btn.getAction());

        datum_tf.setEnabled(false);
        
   
        
        
        if (val_cb.getSelectedItem().toString().equals("Kategori (Områdeschef)"))
        {
            sok_agent_tf.setText("Områdeschef");
            sok_agent_tf.setEnabled(false);
        }
        else if(val_cb.getSelectedItem().toString().equals("Kategori (Fältagent)"))
        {
            sok_agent_tf.setText("Fältagent");
            sok_agent_tf.setEnabled(false);
        }
        else if(val_cb.getSelectedItem().toString().equals("Kategori (Kontorschef)"))
        {
            sok_agent_tf.setText("Kontorschef");
            sok_agent_tf.setEnabled(false);
        }

        if (val_cb.getSelectedItem().toString().equals("Anställningsdatum"))
        {
            datum_tf.setEnabled(true);
        }

    }//GEN-LAST:event_val_cbActionPerformed

    private void sok_agent_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sok_agent_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sok_agent_tfActionPerformed

    private void sok_agent_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sok_agent_btnActionPerformed
//Metod för att söka en agent.        
        model.setRowCount(0);
        datum = datum_tf.getText();
        
        sok = sok_agent_tf.getText().substring(0,1).toUpperCase() + sok_agent_tf.getText().substring(1);
        
        
        sok_agent_btn.addActionListener(val_cb.getAction());
        if(Validering.finnsIngenTabell(agent_tb, sok_agent_tf, val_cb))
        {
            if(val_cb.getSelectedItem().toString().equals("Namn"))
        {
            val = "where agent.Namn like '%"+sok+"%'";
            System.out.println("Namn vald");
        }
        else if(val_cb.getSelectedItem().toString().equals("Anställningsdatum"))
        {
            datum_tf.setEnabled(true);

            if(datum_tf.getText().isEmpty())
            {
                val = "where agent.Anstallningsdatum like '"+sok+"%'";
            }
            else
            {
                    val = "WHERE DATE_FORMAT(agent.Anstallningsdatum, '%Y-%m-%d') >= '"+sok+"' AND DATE_FORMAT(agent.Anstallningsdatum, '%Y-%m-%d') <= '"+datum+"%';";
            }
        }
        else if(val_cb.getSelectedItem().toString().equals("ID"))
        {
            val = "where agent.Agent_ID = "+sok+"";
        }
        
        else if(val_cb.getSelectedItem().toString().equals("Område"))
        {

            val = "where omrade.Benamning like '"+sok+"%'";
        }
        else if(val_cb.getSelectedItem().toString().equals("Telefonnummer"))
        {
            val = "where agent.Telefon like '"+sok+"%'";
        }
        else if(val_cb.getSelectedItem().toString().equals("Epost"))
        {
            val = "where agent.Epost like '"+sok+"%'";
        }

//Här hämtas informationen om en agent och uppdaterar tabellen med den informationen.
        try {
            String hemta_rad_id = "SELECT agent.Namn AS 'Namn', agent.Telefon, agent.Agent_ID, agent.Anstallningsdatum, agent.Epost, agent.Losenord,agent.Administrator, Benamning AS 'Omrade', concat(faltagent.Agent_ID, omradeschef.Agent_ID, kontorschef.Agent_ID) AS 'Kategori' from agent\n" +
"            LEFT JOIN agent AS kontorschef ON agent.Agent_ID = kontorschef.Agent_ID\n" +
"            LEFT JOIN agent AS omradeschef ON agent.Agent_ID = omradeschef.Agent_ID\n" +
"            LEFT JOIN agent AS faltagent ON agent.Agent_ID = faltagent.Agent_ID\n" +
"            join omrade on omrade.Omrades_ID = agent.Omrade " + val+";";
            if(val_cb.getSelectedItem().toString().equals("Kategori (Områdeschef)"))
            {
                hemta_rad_id = "SELECT * from omradeschef join agent on omradeschef.Agent_ID = agent.Agent_ID join omrade on omrade.Omrades_ID = agent.Omrade;";
            }
            if(val_cb.getSelectedItem().toString().equals("Kategori (Kontorschef)"))
            {
                hemta_rad_id = "SELECT * from kontorschef join agent on kontorschef.Agent_ID = agent.Agent_ID join omrade on omrade.Omrades_ID = agent.Omrade;";
            }
            if(val_cb.getSelectedItem().toString().equals("Kategori (Fältagent)"))
            {
                hemta_rad_id = "SELECT * from faltagent join agent on faltagent.Agent_ID = agent.Agent_ID join omrade on omrade.Omrades_ID = agent.Omrade;";
            }

            ArrayList<HashMap<String, String>> info = idb.fetchRows(hemta_rad_id);
            for(HashMap<String,String> allt : info)
            {
                String namn = idb.fetchSingle("select Namn from agent where Agent_ID = "+allt.get("Agent_ID"));
                String id  = allt.get("Agent_ID");
                String ansDatum = allt.get("Anstallningsdatum");
                String epost = allt.get("Epost");
                String losen = allt.get("Losenord");
                String tnr = allt.get("Telefon");
                String omrade = allt.get("Benamning");
                String admin = allt.get("Administrator");
                String kategori = getBefattning(id);
                
                if(admin.equals("J"))
                {
                    admin = "Ja";
                    
                }else{
                    admin = "Nej";
                }
                model.addRow(new Object[]{id,ansDatum,epost,losen,namn,tnr,omrade,admin,kategori});
            }

            model.fireTableDataChanged();
        } catch (InfException ex) {
            Logger.getLogger(soka_agent.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        

        if(sok_agent_tf.getText().isEmpty())
        {
            model.setRowCount(0);
        }
        sok_agent_tf.setText("");
        val="";
        datum_tf.setEnabled(false);
        val_cb.setSelectedIndex(0);
        datum_tf.setText("");
    }//GEN-LAST:event_sok_agent_btnActionPerformed

    private void tillbaka_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tillbaka_btnActionPerformed
        // TODO add your handling code here:
        Andra_sidan andra_sidan = new Andra_sidan(idb, email_L.getText());
        andra_sidan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tillbaka_btnActionPerformed

    private void avsluta_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avsluta_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_avsluta_btnActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(soka_agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(soka_agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(soka_agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(soka_agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new soka_agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agent_L;
    private javax.swing.JTable agent_tb;
    private javax.swing.JButton avsluta_btn;
    private javax.swing.JTextField datum_tf;
    private javax.swing.JLabel email_L;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sok_agent_btn;
    private javax.swing.JTextField sok_agent_tf;
    private javax.swing.JButton tillbaka_btn;
    private javax.swing.JComboBox<String> val_cb;
    // End of variables declaration//GEN-END:variables
}
